bioimageio_core_version: 0.5.1
bioimageio_spec_version: 0.4.5post3
error: 'PytorchStreamReader failed reading zip archive: failed finding central directory'
name: reproduce test outputs with ilastik <todo version> (draft) using pytorch_state_dict
  weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 148, in test_resource\n    bioimageio_model=model, devices=devices, weight_format=weight_format\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
    line 103, in __enter__\n    self.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
    line 143, in load\n    self._model.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
    line 41, in load\n    self._load(devices=devices or self.default_devices)\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_pytorch_model_adapter.py\",
    line 30, in _load\n    state = torch.load(weights.source, map_location=self._devices[0])\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/torch/serialization.py\",
    line 600, in load\n    with _open_zipfile_reader(opened_file) as opened_zipfile:\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/torch/serialization.py\",
    line 242, in __init__\n    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))\n"]
